canonical: http://hl7.org/fhir/us/mcode
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: hl7.fhir.us.mcode
name: UsMcode
status: active
version: 2.1.0
dependencies:
  hl7.fhir.us.core: 4.1.0
  hl7.fhir.us.mcode: 2.0.0
